# Generated by Django 4.2 on 2026-10-02 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('term', models.CharField(choices=[('first', 'First Term'), ('mid', 'Mid Term'), ('second', 'Second Term'), ('final', 'Final Term')], default='first', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datesheets', to='common.academicyear')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datesheets', to='common.schoolclass')),
            ],
            options={
                'ordering': ['-academic_year', 'school_class'],
            },
        ),
        migrations.CreateModel(
            name='DateSheetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(blank=True, max_length=50)),
                ('instructions', models.TextField(blank=True)),
                ('datesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='datesheets.datesheet')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.subject')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
