"""Report center — index page; PDFs are generated by individual apps."""
from django.urls import path
from . import views

app_name = "reports"

urlpatterns = [
    path("", views.ReportIndexView.as_view(), name="index"),
    path("students/", views.StudentReportView.as_view(), name="student_report"),
    path("fees/", views.FeeReportView.as_view(), name="fee_report"),
    path("attendance/", views.AttendanceReportView.as_view(), name="attendance_report"),
    path("payroll/", views.PayrollReportView.as_view(), name="payroll_report"),
    path("defaulter/pdf/", views.DefaulterReportPDFView.as_view(), name="defaulter_pdf"),
]
