# Generated by Django 4.2.30 on 2026-10-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='subject_group',
            field=models.CharField(blank=True, choices=[('', '—'), ('computer', 'Computer Science'), ('bio', 'Biology'), ('pre_med', 'Pre-Medical'), ('pre_eng', 'Pre-Engineering'), ('general', 'General')], db_index=True, default='', help_text="For Grade 9-10: Computer or Biology; lower grades leave as '—'.", max_length=10),
        ),
    ]
