# Generated by Django 4.2 on 2026-10-02 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeChallan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challan_no', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('month', models.CharField(blank=True, help_text='e.g. October 2026', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('unpaid', 'Unpaid'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], db_index=True, default='unpaid', max_length=10)),
                ('is_admission_challan', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_challans', to='common.academicyear')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_challans', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_challans', to='students.student')),
            ],
            options={
                'ordering': ['-issue_date', 'challan_no'],
            },
        ),
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('fee_type', models.CharField(choices=[('tuition', 'Tuition'), ('admission', 'Admission'), ('annual', 'Annual Charges'), ('examination', 'Examination'), ('transport', 'Transport'), ('library', 'Library'), ('computer', 'Computer'), ('sports', 'Sports'), ('lab', 'Lab'), ('uniform', 'Uniform'), ('stationery', 'Stationery'), ('fine', 'Fine'), ('other', 'Other')], db_index=True, default='tuition', max_length=15)),
                ('description', models.TextField(blank=True)),
                ('default_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_no', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card'), ('online', 'Online'), ('other', 'Other')], default='cash', max_length=15)),
                ('transaction_ref', models.CharField(blank=True, max_length=100)),
                ('is_successful', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
                ('challan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='fees.feechallan')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payment_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FeeChallanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('challan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fees.feechallan')),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fees.feetype')),
            ],
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('applies_monthly', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='common.academicyear')),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='structures', to='fees.feetype')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='common.schoolclass')),
            ],
            options={
                'ordering': ['academic_year', 'school_class', 'fee_type'],
                'unique_together': {('academic_year', 'school_class', 'fee_type')},
            },
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['is_successful', 'payment_date'], name='fees_feepay_is_succ_cbdae0_idx'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['challan'], name='fees_feepay_challan_e0f69f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feechallanitem',
            unique_together={('challan', 'fee_type')},
        ),
        migrations.AddIndex(
            model_name='feechallan',
            index=models.Index(fields=['status'], name='fees_feecha_status_ef8592_idx'),
        ),
        migrations.AddIndex(
            model_name='feechallan',
            index=models.Index(fields=['academic_year', 'month'], name='fees_feecha_academi_ea04f6_idx'),
        ),
        migrations.AddIndex(
            model_name='feechallan',
            index=models.Index(fields=['student', 'academic_year'], name='fees_feecha_student_8e9fb2_idx'),
        ),
    ]
