"""Generate remaining templates in batch."""
import os
BASE = "/home/z/my-project/school_erp/templates"

TEMPLATES = {
# Admissions
"admissions/application_list.html": """{% extends "base.html" %}
{% block content %}
<div class="d-flex justify-content-between align-items-center mb-3">
<h1 class="h3 fw-bold mb-0">Admissions</h1>
{% if perms.admissions.add_admission %}
<a href="{% url 'admissions:application_create' %}" class="btn btn-primary"><i class="bi bi-person-plus me-1"></i>New Application</a>
{% endif %}
</div>
<div class="card mb-3"><div class="card-body">
<form method="get" class="row g-2">
<div class="col-md-4"><input type="text" name="q" class="form-control" placeholder="Application #, name" value="{{ request.GET.q }}"></div>
<div class="col-md-3"><select name="status" class="form-select"><option value="">— All Statuses —</option>{% for s,label in status_choices %}<option value="{{ s }}" {% if request.GET.status == s %}selected{% endif %}>{{ label }}</option>{% endfor %}</select></div>
<div class="col-md-2"><button class="btn btn-outline-primary w-100">Filter</button></div>
</form>
</div></div>
<div class="card"><div class="card-body p-0">
{% if admissions %}
<table class="table table-hover mb-0">
<thead><tr><th>Application #</th><th>Student</th><th>Father</th><th>Class</th><th>Year</th><th>Status</th><th>Date</th><th class="text-end">Actions</th></tr></thead>
<tbody>
{% for a in admissions %}
<tr>
<td><strong class="text-primary">{{ a.application_no|default:"—" }}</strong></td>
<td><a href="{% url 'admissions:application_detail' a.pk %}">{{ a.full_name }}</a></td>
<td>{{ a.father_name|default:"—" }}</td>
<td>{{ a.applying_class.name }}{% if a.applying_section %}-{{ a.applying_section.name }}{% endif %}</td>
<td>{{ a.academic_year.name }}</td>
<td><span class="badge badge-status badge-{{ a.status }}">{{ a.get_status_display }}</span></td>
<td>{{ a.admission_date|date:"M d, Y" }}</td>
<td class="text-end"><a href="{% url 'admissions:application_detail' a.pk %}" class="btn btn-sm btn-outline-primary"><i class="bi bi-eye"></i></a></td>
</tr>
{% endfor %}
</tbody>
</table>
{% else %}
<div class="empty-state"><i class="bi bi-person-plus"></i></div>
{% endif %}
</div></div>
{% if is_paginated %}
<div class="mt-3 d-flex justify-content-between"><span class="small text-muted-2">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span><nav><ul class="pagination pagination-sm">{% if page_obj.has_previous %}<li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Prev</a></li>{% endif %}{% if page_obj.has_next %}<li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>{% endif %}</ul></nav></div>
{% endif %}
{% endblock %}
""",
"admissions/application_form.html": """{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<h1 class="h3 fw-bold mb-3">{% if object %}Edit Application{% else %}New Admission Application{% endif %}</h1>
<div class="card"><div class="card-body">
<form method="post">{% csrf_token %}{{ form|crispy }}
<div class="d-flex gap-2 mt-3"><button class="btn btn-primary"><i class="bi bi-check-lg me-1"></i>Save Application (Draft)</button><a href="{% url 'admissions:application_list' %}" class="btn btn-outline-secondary">Cancel</a></div>
</form>
</div></div>
{% endblock %}
""",
"admissions/application_detail.html": """{% extends "base.html" %}
{% block content %}
<div class="d-flex justify-content-between align-items-center mb-3">
<h1 class="h3 fw-bold mb-0">{{ admission.application_no|default:"Draft Application" }}</h1>
<span class="badge badge-status badge-{{ admission.status }} p-2">{{ admission.get_status_display }}</span>
</div>

<div class="card mb-4">
<div class="card-body">
<h6>Workflow Progress</h6>
<div class="d-flex justify-content-between align-items-center mt-3">
{% for label, value in workflow_steps %}
<div class="text-center flex-grow-1">
<div class="badge rounded-pill {% if admission.status == value %}bg-primary{% elif admission.status == 'completed' or forloop.counter < 6 %}bg-success{% else %}bg-light text-dark border{% endif %} p-3" style="width:36px;height:36px;border-radius:50%!important">{{ forloop.counter }}</div>
<div class="small mt-1 {% if admission.status == value %}fw-bold{% endif %}">{{ label }}</div>
</div>
{% if not forloop.last %}<div class="flex-grow-1"><hr class="my-0"></div>{% endif %}
{% endfor %}
</div>
</div>
</div>

<div class="row g-3">
<div class="col-md-6"><div class="card"><div class="card-header">Personal Information</div><div class="card-body p-0"><table class="table mb-0">
<tr><th class="w-40">Name</th><td>{{ admission.full_name }}</td></tr>
<tr><th>Father</th><td>{{ admission.father_name|default:"—" }}</td></tr>
<tr><th>Mother</th><td>{{ admission.mother_name|default:"—" }}</td></tr>
<tr><th>Date of Birth</th><td>{{ admission.date_of_birth|date:"M d, Y"|default:"—" }}</td></tr>
<tr><th>Gender</th><td>{{ admission.get_gender_display }}</td></tr>
<tr><th>CNIC/B-Form</th><td>{{ admission.cnic_bform|default:"—" }}</td></tr>
<tr><th>Contact</th><td>{{ admission.contact_phone|default:"—" }}</td></tr>
<tr><th>Address</th><td>{{ admission.address|default:"—" }}</td></tr>
</table></div></div></div>
<div class="col-md-6"><div class="card"><div class="card-header">Academic & Parent Info</div><div class="card-body p-0"><table class="table mb-0">
<tr><th class="w-40">Applying for Class</th><td>{{ admission.applying_class.name }}{% if admission.applying_section %}-{{ admission.applying_section.name }}{% endif %}</td></tr>
<tr><th>Academic Year</th><td>{{ admission.academic_year.name }}</td></tr>
<tr><th>Admission Date</th><td>{{ admission.admission_date|date:"M d, Y" }}</td></tr>
<tr><th>Previous School</th><td>{{ admission.previous_school|default:"—" }}</td></tr>
<tr><th>Previous Class</th><td>{{ admission.previous_class|default:"—" }}</td></tr>
<tr><th>Parent Name</th><td>{{ admission.parent_name|default:"—" }}</td></tr>
<tr><th>Parent CNIC</th><td>{{ admission.parent_cnic|default:"—" }}</td></tr>
<tr><th>Parent Phone</th><td>{{ admission.parent_phone|default:"—" }}</td></tr>
</table></div></div></div>
</div>

<div class="mt-3">
{% if perms.admissions.change_admission %}
{% if admission.status == 'draft' %}<form method="post" action="{% url 'admissions:application_submit' admission.pk %}" class="d-inline">{% csrf_token %}<button class="btn btn-primary"><i class="bi bi-send me-1"></i>Submit Application</button></form>{% endif %}
{% if admission.status == 'submitted' %}<form method="post" action="{% url 'admissions:application_verify' admission.pk %}" class="d-inline">{% csrf_token %}<button class="btn btn-info"><i class="bi bi-check2-circle me-1"></i>Verify</button></form>{% endif %}
{% if admission.status == 'verified' %}<form method="post" action="{% url 'admissions:application_approve' admission.pk %}" class="d-inline">{% csrf_token %}<button class="btn btn-success"><i class="bi bi-check-circle me-1"></i>Approve</button></form>{% endif %}
{% if admission.status == 'verified' or admission.status == 'submitted' %}<form method="post" action="{% url 'admissions:application_reject' admission.pk %}" class="d-inline">{% csrf_token %}<button class="btn btn-danger"><i class="bi bi-x-circle me-1"></i>Reject</button></form>{% endif %}
{% if admission.status == 'approved' %}<form method="post" action="{% url 'admissions:application_register' admission.pk %}" class="d-inline">{% csrf_token %}<button class="btn btn-primary"><i class="bi bi-person-check me-1"></i>Register Student</button></form>{% endif %}
{% if admission.status == 'approved' or admission.status == 'registered' %}<form method="post" action="{% url 'admissions:application_generate_challan' admission.pk %}" class="d-inline">{% csrf_token %}<button class="btn btn-outline-success"><i class="bi bi-receipt me-1"></i>Generate Admission Challan</button></form>{% endif %}
{% endif %}
{% if perms.admissions.change_admission %}<a href="{% url 'admissions:application_edit' admission.pk %}" class="btn btn-outline-secondary"><i class="bi bi-pencil me-1"></i>Edit</a>{% endif %}
<a href="{% url 'admissions:application_list' %}" class="btn btn-outline-secondary">Back</a>
</div>

{% if admission.admission_challan %}
<div class="card mt-3"><div class="card-header">Linked Admission Challan</div><div class="card-body"><a href="{% url 'fees:challan_detail' admission.admission_challan.pk %}" class="btn btn-success"><i class="bi bi-receipt me-1"></i>{{ admission.admission_challan.challan_no }} — {{ currency_symbol }}{{ admission.admission_challan.total_payable|floatformat:0 }}</a></div></div>
{% endif %}
{% if admission.student %}
<div class="card mt-3"><div class="card-header">Linked Student Record</div><div class="card-body"><a href="{% url 'students:student_detail' admission.student.pk %}" class="btn btn-primary"><i class="bi bi-mortarboard me-1"></i>{{ admission.student.full_name }} — {{ admission.student.registration_no }}</a></div></div>
{% endif %}
{% endblock %}
""",
# Attendance
"attendance/mark.html": """{% extends "base.html" %}
{% block content %}
<h1 class="h3 fw-bold mb-3"><i class="bi bi-check2-square me-2 text-primary"></i>Mark Daily Attendance</h1>
<div class="card mb-3"><div class="card-body"><form method="get" class="row g-2">{% for field in class_filter_form %}{% if field.name != 'subject' %}<div class="col-md-3">{{ field.label_tag }}{{ field }}</div>{% endif %}{% endfor %}<div class="col-md-1 align-self-end"><button class="btn btn-outline-primary w-100"><i class="bi bi-search"></i></button></div></form></div></div>
{% if formset %}
<div class="card"><div class="card-header d-flex justify-content-between align-items-center"><span>Students — {{ selected_class.name }} on {{ selected_date }}</span><button type="button" class="btn btn-sm btn-outline-success" onclick="document.querySelectorAll('select[name^="form-"][name$="-status"]').forEach(function(s){s.value="present";})"><i class="bi bi-check2-all me-1"></i>Mark All Present</button></div>
<div class="card-body">
<form method="post">{% csrf_token %}{{ formset.management_form }}
<input type="hidden" name="school_class" value="{{ selected_class.pk }}">
<input type="hidden" name="section" value="{{ request.GET.section }}">
<input type="hidden" name="date" value="{{ selected_date }}">
<input type="hidden" name="subject" value="{{ selected_subject_id }}">
<table class="table">
<thead><tr><th>Student</th><th>Status</th><th>Notes</th></tr></thead>
<tbody>
{% for form in formset %}
<tr><td>{{ form.student_name }}{{ form.student_id }}</td><td>{{ form.status }}</td><td>{{ form.notes }}</td></tr>
{% endfor %}
</tbody>
</table>
<button class="btn btn-primary"><i class="bi bi-check-lg me-1"></i>Save Attendance</button>
</form>
</div></div>
{% else %}
<div class="empty-state"><i class="bi bi-info-circle"></i><p>Select a class and date above to mark attendance.</p></div>
{% endif %}
{% endblock %}
""",
"attendance/report.html": """{% extends "base.html" %}
{% block content %}
<h1 class="h3 fw-bold mb-3">Attendance Report</h1>
<div class="card mb-3"><div class="card-body"><form method="get" class="row g-2">
<div class="col-md-4"><input type="text" name="q" class="form-control" placeholder="Student name or registration #" value="{{ request.GET.q }}"></div>
<div class="col-md-3"><select name="class" class="form-select"><option value="">— All Classes —</option>{% for c in classes %}<option value="{{ c.pk }}" {% if request.GET.class == c.pk|stringformat:"s" %}selected{% endif %}>{{ c.name }}</option>{% endfor %}</select></div>
<div class="col-md-3"><input type="date" name="date" class="form-control" value="{{ request.GET.date }}"></div>
<div class="col-md-2"><button class="btn btn-outline-primary w-100">Filter</button></div>
</form></div></div>
<div class="card"><div class="card-body p-0">{% if records %}<table class="table table-hover mb-0"><thead><tr><th>Student</th><th>Class</th><th>Date</th><th>Status</th><th>Marked By</th></tr></thead><tbody>{% for r in records %}<tr><td><a href="{% url 'students:student_detail' r.student_id %}">{{ r.student.full_name }}</a></td><td>{{ r.school_class.name }}</td><td>{{ r.date|date:"M d, Y" }}</td><td><span class="badge {% if r.status == 'present' %}bg-soft-success{% elif r.status == 'absent' %}bg-soft-danger{% elif r.status == 'late' %}bg-soft-warning{% else %}bg-soft-info{% endif %}">{{ r.get_status_display }}</span></td><td>{{ r.marked_by|default:"—" }}</td></tr>{% endfor %}</tbody></table>{% else %}<div class="empty-state"><i class="bi bi-clipboard-data"></i><p>No attendance records.</p></div>{% endif %}</div></div>
{% endblock %}
""",
# Diary
"diary/entry_list.html": """{% extends "base.html" %}
{% block content %}
<div class="d-flex justify-content-between align-items-center mb-3">
<h1 class="h3 fw-bold mb-0">Daily Diary</h1>
{% if perms.diary.add_diaryentry %}<a href="{% url 'diary:entry_create' %}" class="btn btn-primary"><i class="bi bi-plus me-1"></i>New Entry</a>{% endif %}
</div>
<div class="card mb-3"><div class="card-body"><form method="get" class="row g-2"><div class="col-md-5"><input type="text" name="q" class="form-control" placeholder="Search topic" value="{{ request.GET.q }}"></div><div class="col-md-4"><select name="class" class="form-select"><option value="">— All Classes —</option>{% for c in classes %}<option value="{{ c.pk }}" {% if request.GET.class == c.pk|stringformat:"s" %}selected{% endif %}>{{ c.name }}</option>{% endfor %}</select></div><div class="col-md-2"><button class="btn btn-outline-primary w-100">Search</button></div></form></div></div>
<div class="row g-3">{% for e in entries %}<div class="col-md-6"><div class="card h-100"><div class="card-body"><div class="d-flex justify-content-between"><div><span class="badge bg-soft-primary">{{ e.date|date:"l, M d, Y" }}</span> <span class="small text-muted-2">{{ e.school_class.name }}{% if e.section %}-{{ e.section.name }}{% endif %}</span></div><span class="small text-muted-2">{{ e.subject.name|default:"" }}</span></div><h5 class="mt-2 mb-1">{{ e.topic }}</h5><p class="small text-muted-2 mb-2">{{ e.lecture_summary|truncatewords:20 }}</p>{% if e.homework %}<p class="small"><strong><i class="bi bi-pencil-square me-1"></i>Homework:</strong> {{ e.homework|truncatewords:15 }}</p>{% endif %}<div class="small text-muted-2 mt-2"><i class="bi bi-person me-1"></i>{{ e.teacher|default:"System" }}</div></div></div></div>{% empty %}<div class="col-12"><div class="empty-state"><i class="bi bi-journal-text"></i><p>No diary entries.</p></div></div>{% endfor %}</div>
{% endblock %}
""",
"diary/entry_form.html": """{% extends "base.html" %}{% load crispy_forms_tags %}{% block content %}<h1 class="h3 fw-bold mb-3">New Diary Entry</h1><div class="card"><div class="card-body"><form method="post">{% csrf_token %}{{ form|crispy }}<button class="btn btn-primary mt-3"><i class="bi bi-check-lg me-1"></i>Save Entry</button><a href="{% url 'diary:entry_list' %}" class="btn btn-outline-secondary mt-3">Cancel</a></form></div></div>{% endblock %}""",
"diary/entry_detail.html": """{% extends "base.html" %}
{% block content %}
<h1 class="h3 fw-bold mb-3">{{ entry.topic }}</h1>
<div class="row g-3"><div class="col-md-8"><div class="card mb-3"><div class="card-header"><i class="bi bi-calendar me-2"></i>{{ entry.date|date:"l, F d, Y" }} · {{ entry.school_class.name }}{% if entry.section %}-{{ entry.section.name }}{% endif %} · {{ entry.subject.name|default:"" }}</div><div class="card-body"><h6>Lecture Summary</h6><p>{{ entry.lecture_summary|linebreaksbr }}</p>{% if entry.homework %}<h6 class="mt-3">Homework</h6><p>{{ entry.homework|linebreaksbr }}</p>{% endif %}{% if entry.important_instructions %}<h6 class="mt-3">Important Instructions</h6><p>{{ entry.important_instructions|linebreaksbr }}</p>{% endif %}{% if entry.notes %}<h6 class="mt-3">Notes</h6><p>{{ entry.notes|linebreaksbr }}</p>{% endif %}</div></div></div><div class="col-md-4"><div class="card"><div class="card-header">Quick Info</div><div class="card-body p-0"><table class="table mb-0"><tr><th>Teacher</th><td>{{ entry.teacher|default:"—" }}</td></tr><tr><th>Class</th><td>{{ entry.school_class.name }}</td></tr><tr><th>Subject</th><td>{{ entry.subject.name|default:"—" }}</td></tr><tr><th>Date</th><td>{{ entry.date|date:"M d, Y" }}</td></tr></table></div></div></div></div>
{% endblock %}
""",
# Homework
"homework/homework_list.html": """{% extends "base.html" %}
{% block content %}
<div class="d-flex justify-content-between align-items-center mb-3">
<h1 class="h3 fw-bold mb-0">Homework</h1>
{% if perms.homework.add_homework %}<a href="{% url 'homework:homework_create' %}" class="btn btn-primary"><i class="bi bi-plus me-1"></i>New Homework</a>{% endif %}
</div>
<div class="card mb-3"><div class="card-body"><form method="get" class="row g-2"><div class="col-md-6"><input type="text" name="q" class="form-control" placeholder="Search" value="{{ request.GET.q }}"></div><div class="col-md-4"><select name="class" class="form-select"><option value="">— All Classes —</option>{% for c in classes %}<option value="{{ c.pk }}">{{ c.name }}</option>{% endfor %}</select></div><div class="col-md-2"><button class="btn btn-outline-primary w-100">Search</button></div></form></div></div>
<div class="card"><div class="card-body p-0">{% if homeworks %}<table class="table table-hover mb-0"><thead><tr><th>Title</th><th>Class</th><th>Subject</th><th>Assigned</th><th>Due</th><th>Status</th><th class="text-end">Actions</th></tr></thead><tbody>{% for h in homeworks %}<tr><td><a href="{% url 'homework:homework_detail' h.pk %}">{{ h.title }}</a></td><td>{{ h.school_class.name }}</td><td>{{ h.subject.name|default:"—" }}</td><td>{{ h.assigned_date|date:"M d" }}</td><td>{{ h.due_date|date:"M d, Y" }}</td><td><span class="badge badge-status badge-{{ h.status }}">{{ h.get_status_display }}</span></td><td class="text-end"><a href="{% url 'homework:homework_detail' h.pk %}" class="btn btn-sm btn-outline-primary"><i class="bi bi-eye"></i></a>{% if perms.homework.change_homework %}<a href="{% url 'homework:homework_edit' h.pk %}" class="btn btn-sm btn-outline-secondary"><i class="bi bi-pencil"></i></a>{% endif %}</td></tr>{% endfor %}</tbody></table>{% else %}<div class="empty-state"><i class="bi bi-pencil-square"></i></div>{% endif %}</div></div>
{% endblock %}
""",
"homework/homework_form.html": """{% extends "base.html" %}{% load crispy_forms_tags %}{% block content %}<h1 class="h3 fw-bold mb-3">{% if object %}Edit Homework{% else %}New Homework{% endif %}</h1><div class="card"><div class="card-body"><form method="post" enctype="multipart/form-data">{% csrf_token %}{{ form|crispy }}<button class="btn btn-primary mt-3"><i class="bi bi-check-lg me-1"></i>Save</button><a href="{% url 'homework:homework_list' %}" class="btn btn-outline-secondary mt-3">Cancel</a></form></div></div>{% endblock %}""",
"homework/homework_detail.html": """{% extends "base.html" %}
{% block content %}
<div class="d-flex justify-content-between align-items-center mb-3"><h1 class="h3 fw-bold mb-0">{{ homework.title }}</h1><span class="badge badge-status badge-{{ homework.status }}">{{ homework.get_status_display }}</span></div>
<div class="card mb-3"><div class="card-header"><i class="bi bi-info-circle me-2"></i>{{ homework.school_class.name }} · {{ homework.subject.name|default:"" }} · Due {{ homework.due_date|date:"M d, Y" }}</div><div class="card-body"><h6>Description</h6><p>{{ homework.description|linebreaksbr }}</p>{% if homework.attachment %}<p><a href="{{ homework.attachment.url }}" class="btn btn-outline-primary"><i class="bi bi-paperclip me-1"></i>Download Attachment</a></p>{% endif %}<hr><p class="small text-muted-2">Assigned by: {{ homework.teacher|default:"System" }} on {{ homework.assigned_date|date:"M d, Y" }}</p></div></div>
{% if perms.homework.change_homework %}<a href="{% url 'homework:homework_edit' homework.pk %}" class="btn btn-outline-primary"><i class="bi bi-pencil me-1"></i>Edit</a>{% endif %}
<a href="{% url 'homework:homework_list' %}" class="btn btn-outline-secondary">Back</a>
{% endblock %}
""",
# Syllabus
"syllabus/syllabus_list.html": """{% extends "base.html" %}
{% block content %}
<div class="d-flex justify-content-between align-items-center mb-3">
<h1 class="h3 fw-bold mb-0">Syllabus</h1>
{% if perms.syllabus.add_syllabus %}<a href="{% url 'syllabus:syllabus_create' %}" class="btn btn-primary"><i class="bi bi-plus me-1"></i>New Syllabus</a>{% endif %}
</div>
<div class="card"><div class="card-body p-0">{% if syllabi %}<table class="table table-hover mb-0"><thead><tr><th>Class</th><th>Subject</th><th>Term</th><th>Year</th><th class="text-end">View</th></tr></thead><tbody>{% for s in syllabi %}<tr><td>{{ s.school_class.name }}</td><td>{{ s.subject.name }}</td><td>{{ s.get_term_display }}</td><td>{{ s.academic_year.name }}</td><td class="text-end"><a href="{% url 'syllabus:syllabus_detail' s.pk %}" class="btn btn-sm btn-outline-primary"><i class="bi bi-eye"></i></a></td></tr>{% endfor %}</tbody></table>{% else %}<div class="empty-state"><i class="bi bi-list-task"></i></div>{% endif %}</div></div>
{% endblock %}
""",
"syllabus/syllabus_form.html": """{% extends "base.html" %}{% load crispy_forms_tags %}{% block content %}<h1 class="h3 fw-bold mb-3">New Syllabus</h1><div class="card"><div class="card-body"><form method="post">{% csrf_token %}{{ form|crispy }}<button class="btn btn-primary mt-3">Save</button><a href="{% url 'syllabus:syllabus_list' %}" class="btn btn-outline-secondary mt-3">Cancel</a></form></div></div>{% endblock %}""",
"syllabus/syllabus_detail.html": """{% extends "base.html" %}
{% block content %}
<div class="d-flex justify-content-between align-items-center mb-3"><h1 class="h3 fw-bold mb-0">{{ syllabus.school_class.name }} — {{ syllabus.subject.name }}</h1>{% if perms.syllabus.add_syllabustopic %}<a href="{% url 'syllabus:topic_create' syllabus.pk %}" class="btn btn-primary btn-sm"><i class="bi bi-plus me-1"></i>Add Topic</a>{% endif %}</div>
<div class="card mb-3"><div class="card-header"><i class="bi bi-bar-chart me-2"></i>Syllabus Progress</div><div class="card-body"><h2 class="display-6 mb-2">{{ progress.percentage }}%</h2><div class="progress" style="height:10px"><div class="progress-bar" style="width: {{ progress.percentage }}%"></div></div><div class="row mt-3 text-center"><div class="col"><div class="fw-bold">{{ progress.completed }}</div><div class="small text-muted-2">Completed</div></div><div class="col"><div class="fw-bold">{{ progress.in_progress }}</div><div class="small text-muted-2">In Progress</div></div><div class="col"><div class="fw-bold text-warning">{{ progress.delayed }}</div><div class="small text-muted-2">Delayed</div></div><div class="col"><div class="fw-bold text-muted-2">{{ progress.not_started }}</div><div class="small text-muted-2">Not Started</div></div></div></div></div>
<div class="card"><div class="card-header">Topics</div><div class="card-body p-0">{% if topics %}<table class="table mb-0"><thead><tr><th>Chapter</th><th>Topic</th><th>Expected</th><th>Actual</th><th>Status</th><th class="text-end">Edit</th></tr></thead><tbody>{% for t in topics %}<tr><td>{{ t.chapter }}</td><td>{{ t.topic }}</td><td>{{ t.expected_completion_date|date:"M d, Y"|default:"—" }}</td><td>{{ t.actual_completion_date|date:"M d, Y"|default:"—" }}</td><td><span class="badge {% if t.status == 'completed' %}badge-paid{% elif t.status == 'in_progress' %}badge-processing{% elif t.status == 'delayed' %}badge-pending{% else %}badge-draft{% endif %}">{{ t.get_status_display }}</span></td><td class="text-end"><a href="{% url 'syllabus:topic_edit' t.pk %}" class="btn btn-sm btn-outline-primary"><i class="bi bi-pencil"></i></a></td></tr>{% endfor %}</tbody></table>{% else %}<div class="empty-state"><i class="bi bi-list"></i><p>No topics yet.</p></div>{% endif %}</div></div>
{% endblock %}
""",
"syllabus/topic_form.html": """{% extends "base.html" %}{% load crispy_forms_tags %}{% block content %}<h1 class="h3 fw-bold mb-3">Topic</h1><div class="card"><div class="card-body"><form method="post">{% csrf_token %}{{ form|crispy }}<button class="btn btn-primary mt-3">Save</button>{% if syllabus %}<a href="{% url 'syllabus:syllabus_detail' syllabus.pk %}" class="btn btn-outline-secondary mt-3">Cancel</a>{% endif %}</form></div></div>{% endblock %}""",
"syllabus/lecture_list.html": """{% extends "base.html" %}{% block content %}<h1 class="h3 fw-bold mb-3">Lecture Planner</h1><div class="d-flex justify-content-end mb-3">{% if perms.syllabus.add_lectureplan %}<a href="{% url 'syllabus:lecture_create' %}" class="btn btn-primary"><i class="bi bi-plus me-1"></i>New Lecture Plan</a>{% endif %}</div><div class="card"><div class="card-body p-0">{% if lectures %}<table class="table mb-0"><thead><tr><th>Date</th><th>Class</th><th>Topic</th><th>Duration</th><th>Status</th></tr></thead><tbody>{% for l in lectures %}<tr><td>{{ l.date|date:"M d, Y" }}</td><td>{{ l.school_class.name }}</td><td>{{ l.topic }}</td><td>{{ l.estimated_duration }} min</td><td><span class="badge badge-status badge-{{ l.status }}">{{ l.get_status_display }}</span></td></tr>{% endfor %}</tbody></table>{% else %}<div class="empty-state"><i class="bi bi-calendar2-plus"></i></div>{% endif %}</div></div>{% endblock %}""",
"syllabus/lecture_form.html": """{% extends "base.html" %}{% load crispy_forms_tags %}{% block content %}<h1 class="h3 fw-bold mb-3">New Lecture Plan</h1><div class="card"><div class="card-body"><form method="post">{% csrf_token %}{{ form|crispy }}<button class="btn btn-primary mt-3">Save</button><a href="{% url 'syllabus:lecture_list' %}" class="btn btn-outline-secondary mt-3">Cancel</a></form></div></div>{% endblock %}""",
# Examinations
"examinations/classtest_list.html": """{% extends "base.html" %}
{% block content %}
<div class="d-flex justify-content-between align-items-center mb-3"><h1 class="h3 fw-bold mb-0">Class Tests</h1>{% if perms.examinations.add_classtest %}<a href="{% url 'examinations:classtest_create' %}" class="btn btn-primary"><i class="bi bi-plus me-1"></i>New Test</a>{% endif %}</div>
<div class="card"><div class="card-body p-0">{% if tests %}<table class="table table-hover mb-0"><thead><tr><th>Title</th><th>Class</th><th>Subject</th><th>Date</th><th>Marks</th><th>Status</th><th class="text-end">Actions</th></tr></thead><tbody>{% for t in tests %}<tr><td><a href="{% url 'examinations:classtest_detail' t.pk %}">{{ t.title }}</a></td><td>{{ t.school_class.name }}</td><td>{{ t.subject.name }}</td><td>{{ t.date|date:"M d, Y" }}</td><td>{{ t.total_marks|floatformat:0 }} (Pass: {{ t.passing_marks|floatformat:0 }})</td><td><span class="badge {% if t.status == 'published' %}badge-paid{% else %}badge-draft{% endif %}">{{ t.get_status_display }}</span></td><td class="text-end"><a href="{% url 'examinations:classtest_detail' t.pk %}" class="btn btn-sm btn-outline-primary"><i class="bi bi-eye"></i></a>{% if perms.examinations.add_testresult %}<a href="{% url 'examinations:classtest_results' t.pk %}" class="btn btn-sm btn-outline-success"><i class="bi bi-pencil-square"></i></a>{% endif %}</td></tr>{% endfor %}</tbody></table>{% else %}<div class="empty-state"><i class="bi bi-card-checklist"></i></div>{% endif %}</div></div>
{% endblock %}
""",
"examinations/classtest_form.html": """{% extends "base.html" %}{% load crispy_forms_tags %}{% block content %}<h1 class="h3 fw-bold mb-3">New Class Test</h1><div class="card"><div class="card-body"><form method="post">{% csrf_token %}{{ form|crispy }}<button class="btn btn-primary mt-3">Save</button><a href="{% url 'examinations:classtest_list' %}" class="btn btn-outline-secondary mt-3">Cancel</a></form></div></div>{% endblock %}""",
"examinations/classtest_detail.html": """{% extends "base.html" %}
{% block content %}
<div class="d-flex justify-content-between align-items-center mb-3"><h1 class="h3 fw-bold mb-0">{{ test.title }}</h1><span class="badge {% if test.status == 'published' %}badge-paid{% else %}badge-draft{% endif %}">{{ test.get_status_display }}</span></div>
<div class="card mb-3"><div class="card-header">Test Information</div><div class="card-body p-0"><table class="table mb-0"><tr><th class="w-25">Title</th><td>{{ test.title }}</td></tr><tr><th>Class</th><td>{{ test.school_class.name }}</td></tr><tr><th>Subject</th><td>{{ test.subject.name }}</td></tr><tr><th>Date</th><td>{{ test.date|date:"M d, Y" }}</td></tr><tr><th>Total Marks</th><td>{{ test.total_marks|floatformat:0 }}</td></tr><tr><th>Passing Marks</th><td>{{ test.passing_marks|floatformat:0 }}</td></tr><tr><th>Topics</th><td>{{ test.topics|default:"—" }}</td></tr></table></div></div>
{% if perms.examinations.add_testresult %}<a href="{% url 'examinations:classtest_results' test.pk %}" class="btn btn-success"><i class="bi bi-pencil-square me-1"></i>Enter / Edit Marks</a>{% endif %}
{% endblock %}
""",
"examinations/classtest_results.html": """{% extends "base.html" %}
{% block content %}
<div class="d-flex justify-content-between align-items-center mb-3"><h1 class="h3 fw-bold mb-0">Enter Marks — {{ test.title }}</h1><span class="badge bg-soft-primary">{{ test.school_class.name }} · {{ test.subject.name }} · {{ test.date|date:"M d, Y" }}</span></div>
<div class="card"><div class="card-body"><form method="post">{% csrf_token %}<table class="table"><thead><tr><th>Student</th><th>Reg. No</th><th>Obtained Marks</th><th>Remarks</th></tr></thead><tbody>{% for s in students %}<tr><td>{{ s.full_name }}</td><td>{{ s.registration_no }}</td><td><input type="number" name="obtained_marks" value="{% for r in test.results.all %}{% if r.student_id == s.pk %}{{ r.obtained_marks|floatformat:0 }}{% endif %}{% endfor %}" step="0.5" max="{{ test.total_marks|floatformat:0 }}" class="form-control form-control-sm" style="width:100px"></td><td><input type="text" name="remarks" value="{% for r in test.results.all %}{% if r.student_id == s.pk %}{{ r.remarks }}{% endif %}{% endfor %}" class="form-control form-control-sm"></td><input type="hidden" name="student_id" value="{{ s.pk }}"></tr>{% endfor %}</tbody></table><button class="btn btn-primary"><i class="bi bi-check-lg me-1"></i>Save Marks</button><a href="{% url 'examinations:classtest_detail' test.pk %}" class="btn btn-outline-secondary">Cancel</a></form></div></div>
{% endblock %}
""",
"examinations/surprisetest_list.html": """{% extends "base.html" %}{% block content %}<div class="d-flex justify-content-between align-items-center mb-3"><h1 class="h3 fw-bold mb-0">Surprise Tests</h1>{% if perms.examinations.add_surprisetest %}<a href="{% url 'examinations:surprisetest_create' %}" class="btn btn-primary"><i class="bi bi-plus me-1"></i>New Surprise Test</a>{% endif %}</div><div class="card"><div class="card-body p-0">{% if tests %}<table class="table mb-0"><thead><tr><th>Title</th><th>Class</th><th>Subject</th><th>Date</th><th>Marks</th><th>Status</th></tr></thead><tbody>{% for t in tests %}<tr><td>{{ t.title }}</td><td>{{ t.school_class.name }}</td><td>{{ t.subject.name }}</td><td>{{ t.date|date:"M d, Y" }}</td><td>{{ t.total_marks|floatformat:0 }}</td><td><span class="badge {% if t.status == 'published' %}badge-paid{% else %}badge-draft{% endif %}">{{ t.get_status_display }}</span></td></tr>{% endfor %}</tbody></table>{% else %}<div class="empty-state"><i class="bi bi-lightning"></i></div>{% endif %}</div></div>{% endblock %}""",
"examinations/surprisetest_form.html": """{% extends "base.html" %}{% load crispy_forms_tags %}{% block content %}<h1 class="h3 fw-bold mb-3">New Surprise Test</h1><div class="card"><div class="card-body"><form method="post">{% csrf_token %}{{ form|crispy }}<button class="btn btn-primary mt-3">Save</button><a href="{% url 'examinations:surprisetest_list' %}" class="btn btn-outline-secondary mt-3">Cancel</a></form></div></div>{% endblock %}""",
"examinations/exam_list.html": """{% extends "base.html" %}{% block content %}<div class="d-flex justify-content-between align-items-center mb-3"><h1 class="h3 fw-bold mb-0">Term Examinations</h1>{% if perms.examinations.add_exam %}<a href="{% url 'examinations:exam_create' %}" class="btn btn-primary"><i class="bi bi-plus me-1"></i>New Term Exam</a>{% endif %}</div><div class="card"><div class="card-body p-0">{% if exams %}<table class="table mb-0"><thead><tr><th>Name</th><th>Term</th><th>Year</th><th>Start</th><th>End</th><th>Published?</th><th class="text-end">View</th></tr></thead><tbody>{% for e in exams %}<tr><td><a href="{% url 'examinations:exam_detail' e.pk %}">{{ e.name }}</a></td><td>{{ e.get_term_display }}</td><td>{{ e.academic_year.name }}</td><td>{{ e.start_date|date:"M d, Y" }}</td><td>{{ e.end_date|date:"M d, Y" }}</td><td>{% if e.is_published %}<i class="bi bi-check-circle text-success"></i>{% else %}<i class="bi bi-x-circle text-danger"></i>{% endif %}</td><td class="text-end"><a href="{% url 'examinations:exam_detail' e.pk %}" class="btn btn-sm btn-outline-primary"><i class="bi bi-eye"></i></a></td></tr>{% endfor %}</tbody></table>{% else %}<div class="empty-state"><i class="bi bi-journal-medical"></i></div>{% endif %}</div></div>{% endblock %}""",
"examinations/exam_form.html": """{% extends "base.html" %}{% load crispy_forms_tags %}{% block content %}<h1 class="h3 fw-bold mb-3">New Term Exam</h1><div class="card"><div class="card-body"><form method="post">{% csrf_token %}{{ form|crispy }}<button class="btn btn-primary mt-3">Save</button><a href="{% url 'examinations:exam_list' %}" class="btn btn-outline-secondary mt-3">Cancel</a></form></div></div>{% endblock %}""",
"examinations/exam_detail.html": """{% extends "base.html" %}{% block content %}<div class="d-flex justify-content-between align-items-center mb-3"><h1 class="h3 fw-bold mb-0">{{ exam.name }}</h1><span class="badge {% if exam.is_published %}badge-paid{% else %}badge-draft{% endif %}">{% if exam.is_published %}Published{% else %}Draft{% endif %}</span></div><div class="card mb-3"><div class="card-header">Exam Details</div><div class="card-body p-0"><table class="table mb-0"><tr><th class="w-25">Term</th><td>{{ exam.get_term_display }}</td></tr><tr><th>Academic Year</th><td>{{ exam.academic_year.name }}</td></tr><tr><th>Start</th><td>{{ exam.start_date|date:"M d, Y" }}</td></tr><tr><th>End</th><td>{{ exam.end_date|date:"M d, Y" }}</td></tr></table></div></div><div class="card"><div class="card-header">Subjects & Schedule</div><div class="card-body p-0">{% if subjects %}<table class="table mb-0"><thead><tr><th>Class</th><th>Subject</th><th>Date</th><th>Total Marks</th><th>Pass</th></tr></thead><tbody>{% for s in subjects %}<tr><td>{{ s.school_class.name }}</td><td>{{ s.subject.name }}</td><td>{{ s.date|date:"M d, Y" }}</td><td>{{ s.total_marks|floatformat:0 }}</td><td>{{ s.passing_marks|floatformat:0 }}</td></tr>{% endfor %}</tbody></table>{% else %}<div class="empty-state"><i class="bi bi-list"></i></div>{% endif %}</div></div>{% endblock %}""",
"examinations/termresult_list.html": """{% extends "base.html" %}{% block content %}<div class="d-flex justify-content-between align-items-center mb-3"><h1 class="h3 fw-bold mb-0">Term Results</h1></div><div class="card mb-3"><div class="card-body"><form method="get"><select name="status" class="form-select"><option value="">— All Statuses —</option>{% for s,label in status_choices %}<option value="{{ s }}" {% if request.GET.status == s %}selected{% endif %}>{{ label }}</option>{% endfor %}</select><button class="btn btn-outline-primary mt-2">Filter</button></form></div></div><div class="card"><div class="card-body p-0">{% if results %}<table class="table table-hover mb-0"><thead><tr><th>Student</th><th>Year</th><th>Term</th><th>Percentage</th><th>Grade</th><th>Rank</th><th>Status</th><th class="text-end">Actions</th></tr></thead><tbody>{% for r in results %}<tr><td><a href="{% url 'students:student_detail' r.student_id %}">{{ r.student.full_name }}</a></td><td>{{ r.academic_year.name }}</td><td>{{ r.get_term_display }}</td><td>{{ r.percentage|floatformat:2 }}%</td><td><span class="badge bg-soft-primary">{{ r.grade }}</span></td><td>{{ r.rank|default:"—" }}</td><td><span class="badge badge-status badge-{{ r.status }}">{{ r.get_status_display }}</span></td><td class="text-end">{% if perms.examinations.change_termresult and r.status != 'published' %}<form method="post" action="{% url 'examinations:termresult_publish' r.pk %}" class="d-inline">{% csrf_token %}<button class="btn btn-sm btn-success"><i class="bi bi-send me-1"></i>Publish</button></form>{% endif %}<a href="{% url 'examinations:report_card_pdf' r.pk %}" target="_blank" class="btn btn-sm btn-outline-danger"><i class="bi bi-file-pdf"></i></a></td></tr>{% endfor %}</tbody></table>{% else %}<div class="empty-state"><i class="bi bi-award"></i></div>{% endif %}</div></div>{% endblock %}""",
"examinations/report_card.html": """{% extends "base.html" %}
{% block content %}
<div class="container" style="max-width: 800px;">
<div class="card"><div class="card-header text-center bg-primary text-white py-4"><h2 class="h4 mb-0">{{ school_name|default:"School ERP" }}</h2><p class="small mb-0">Academic Report Card</p></div>
<div class="card-body"><div class="row mb-4"><div class="col-6"><p class="mb-0"><strong>Student:</strong> {{ student.full_name }}</p><p class="mb-0"><strong>Registration:</strong> {{ student.registration_no }}</p><p class="mb-0"><strong>Father:</strong> {{ student.father_name|default:"—" }}</p></div><div class="col-6 text-end"><p class="mb-0"><strong>Class:</strong> {{ student.class_section_display }}</p><p class="mb-0"><strong>Year:</strong> {{ result.academic_year.name }}</p><p class="mb-0"><strong>Term:</strong> {{ result.get_term_display }}</p></div></div>
<table class="table table-bordered"><tr class="table-active"><th>Total Marks</th><th>Obtained</th><th>Percentage</th><th>Grade</th><th>Rank</th></tr><tr class="text-center"><td>{{ result.total_marks|floatformat:0 }}</td><td>{{ result.obtained_marks|floatformat:2 }}</td><td>{{ result.percentage|floatformat:2 }}%</td><td><strong>{{ result.grade }}</strong></td><td>{{ result.rank|default:"—" }}</td></tr></table>
{% if result.teacher_remarks %}<div class="mt-3"><strong>Teacher Remarks:</strong><p>{{ result.teacher_remarks|linebreaksbr }}</p></div>{% endif %}{% if result.principal_remarks %}<div class="mt-3"><strong>Principal Remarks:</strong><p>{{ result.principal_remarks|linebreaksbr }}</p></div>{% endif %}
<p class="small text-muted-2 mt-4">This report card is computer-generated and does not require a physical signature.</p>
</div></div></div>
{% endblock %}
""",
# Datesheets
"datesheets/datesheet_list.html": """{% extends "base.html" %}{% block content %}<div class="d-flex justify-content-between align-items-center mb-3"><h1 class="h3 fw-bold mb-0">Date Sheets</h1>{% if perms.datesheets.add_datesheet %}<a href="{% url 'datesheets:datesheet_create' %}" class="btn btn-primary"><i class="bi bi-plus me-1"></i>New Date Sheet</a>{% endif %}</div><div class="card"><div class="card-body p-0">{% if datesheets %}<table class="table table-hover mb-0"><thead><tr><th>Title</th><th>Class</th><th>Term</th><th>Year</th><th>Status</th><th class="text-end">View</th></tr></thead><tbody>{% for d in datesheets %}<tr><td><a href="{% url 'datesheets:datesheet_detail' d.pk %}">{{ d.title }}</a></td><td>{{ d.school_class.name }}</td><td>{{ d.get_term_display }}</td><td>{{ d.academic_year.name }}</td><td><span class="badge {% if d.status == 'published' %}badge-paid{% else %}badge-draft{% endif %}">{{ d.get_status_display }}</span></td><td class="text-end"><a href="{% url 'datesheets:datesheet_detail' d.pk %}" class="btn btn-sm btn-outline-primary"><i class="bi bi-eye"></i></a></td></tr>{% endfor %}</tbody></table>{% else %}<div class="empty-state"><i class="bi bi-calendar-week"></i></div>{% endif %}</div></div>{% endblock %}""",
"datesheets/datesheet_form.html": """{% extends "base.html" %}{% load crispy_forms_tags %}{% block content %}<h1 class="h3 fw-bold mb-3">New Date Sheet</h1><div class="card"><div class="card-body"><form method="post">{% csrf_token %}{{ form|crispy }}<button class="btn btn-primary mt-3">Save</button><a href="{% url 'datesheets:datesheet_list' %}" class="btn btn-outline-secondary mt-3">Cancel</a></form></div></div>{% endblock %}""",
"datesheets/datesheet_detail.html": """{% extends "base.html" %}{% block content %}<div class="d-flex justify-content-between align-items-center mb-3"><h1 class="h3 fw-bold mb-0">{{ datesheet.title }}</h1>{% if perms.datesheets.change_datesheet and datesheet.status != 'published' %}<form method="post" action="{% url 'datesheets:datesheet_publish' datesheet.pk %}" class="d-inline">{% csrf_token %}<button class="btn btn-success btn-sm"><i class="bi bi-send me-1"></i>Publish</button></form>{% endif %}</div><div class="card mb-3"><div class="card-header">Details</div><div class="card-body p-0"><table class="table mb-0"><tr><th class="w-25">Class</th><td>{{ datesheet.school_class.name }}</td></tr><tr><th>Term</th><td>{{ datesheet.get_term_display }}</td></tr><tr><th>Academic Year</th><td>{{ datesheet.academic_year.name }}</td></tr><tr><th>Status</th><td><span class="badge {% if datesheet.status == 'published' %}badge-paid{% else %}badge-draft{% endif %}">{{ datesheet.get_status_display }}</span></td></tr></table></div></div><div class="card"><div class="card-header">Schedule</div><div class="card-body p-0">{% if items %}<table class="table table-hover mb-0"><thead><tr><th>Date</th><th>Subject</th><th>Time</th><th>Room</th><th>Instructions</th></tr></thead><tbody>{% for i in items %}<tr><td>{{ i.date|date:"l, M d, Y" }}</td><td>{{ i.subject.name }}</td><td>{{ i.start_time|time:"H:i" }} - {{ i.end_time|time:"H:i" }}</td><td>{{ i.room|default:"—" }}</td><td>{{ i.instructions|default:"—" }}</td></tr>{% endfor %}</tbody></table>{% else %}<div class="empty-state"><i class="bi bi-calendar"></i><p>No items yet.</p></div>{% endif %}</div></div>{% if perms.datesheets.add_datesheetitem %}<div class="card mt-3"><div class="card-header">Add Item</div><div class="card-body"><form method="post" action="{% url 'datesheets:item_create' datesheet.pk %}">{% csrf_token %}{{ item_form|crispy }}<button class="btn btn-primary mt-2">Add</button></form></div></div>{% endif %}{% endblock %}""",
# Payroll
"payroll/payroll_list.html": """{% extends "base.html" %}
{% block content %}
<div class="d-flex justify-content-between align-items-center mb-3"><h1 class="h3 fw-bold mb-0">Teacher Payroll</h1>{% if perms.payroll.add_payroll %}<a href="{% url 'payroll:payroll_create' %}" class="btn btn-primary"><i class="bi bi-plus me-1"></i>Generate Payroll</a>{% endif %}</div>
<div class="card mb-3"><div class="card-body"><form method="get" class="row g-2"><div class="col-md-4"><input type="text" name="q" class="form-control" placeholder="Teacher name or employee ID" value="{{ request.GET.q }}"></div><div class="col-md-3"><select name="status" class="form-select"><option value="">— All Statuses —</option>{% for s,label in status_choices %}<option value="{{ s }}" {% if request.GET.status == s %}selected{% endif %}>{{ label }}</option>{% endfor %}</select></div><div class="col-md-2"><button class="btn btn-outline-primary w-100">Filter</button></div></form></div></div>
<div class="card"><div class="card-body p-0">{% if payrolls %}<table class="table table-hover mb-0"><thead><tr><th>Teacher</th><th>Employee ID</th><th>Month</th><th>Basic</th><th>Allow.</th><th>Deduct.</th><th>Net</th><th>Status</th><th class="text-end">Actions</th></tr></thead><tbody>{% for p in payrolls %}<tr><td><a href="{% url 'teachers:teacher_detail' p.teacher_id %}">{{ p.teacher.full_name }}</a></td><td>{{ p.teacher.employee_id }}</td><td>{{ p.month }}</td><td>{{ currency_symbol }}{{ p.basic_salary|floatformat:0|intcomma }}</td><td>{{ currency_symbol }}{{ p.allowances|floatformat:0 }}</td><td>{{ currency_symbol }}{{ p.deductions|floatformat:0 }}</td><td class="fw-bold">{{ currency_symbol }}{{ p.net_salary|floatformat:0|intcomma }}</td><td><span class="badge badge-status badge-{{ p.status }}">{{ p.get_status_display }}</span></td><td class="text-end"><a href="{% url 'payroll:payroll_detail' p.pk %}" class="btn btn-sm btn-outline-primary"><i class="bi bi-eye"></i></a><a href="{% url 'payroll:salary_slip_pdf' p.pk %}" target="_blank" class="btn btn-sm btn-outline-danger"><i class="bi bi-file-pdf"></i></a></td></tr>{% endfor %}</tbody></table>{% else %}<div class="empty-state"><i class="bi bi-cash-coin"></i></div>{% endif %}</div></div>
{% endblock %}
""",
"payroll/payroll_form.html": """{% extends "base.html" %}{% load crispy_forms_tags %}{% block content %}<h1 class="h3 fw-bold mb-3">Generate Payroll</h1><div class="card"><div class="card-body"><form method="post">{% csrf_token %}{{ form|crispy }}<button class="btn btn-primary mt-3">Generate</button><a href="{% url 'payroll:payroll_list' %}" class="btn btn-outline-secondary mt-3">Cancel</a></form></div></div>{% endblock %}""",
"payroll/payroll_detail.html": """{% extends "base.html" %}
{% block content %}
<div class="d-flex justify-content-between align-items-center mb-3"><h1 class="h3 fw-bold mb-0">Payroll — {{ payroll.teacher.full_name }}</h1><div>{% if payroll.status == 'draft' and perms.payroll.change_payroll %}<form method="post" action="{% url 'payroll:payroll_approve' payroll.pk %}" class="d-inline">{% csrf_token %}<button class="btn btn-success btn-sm"><i class="bi bi-check-circle me-1"></i>Approve</button></form>{% endif %}{% if payroll.status == 'approved' and perms.payroll.add_salarypayment %}<a href="{% url 'payroll:payroll_pay' payroll.pk %}" class="btn btn-primary btn-sm"><i class="bi bi-bank me-1"></i>Record Bank Payment</a>{% endif %}<a href="{% url 'payroll:salary_slip_pdf' payroll.pk %}" target="_blank" class="btn btn-outline-danger btn-sm"><i class="bi bi-file-pdf me-1"></i>Salary Slip PDF</a></div></div>
<div class="row g-3"><div class="col-md-8"><div class="card mb-3"><div class="card-header">Salary Components</div><div class="card-body p-0"><table class="table mb-0"><tr><th>Basic Salary</th><td class="text-end">{{ currency_symbol }}{{ payroll.basic_salary|floatformat:0|intcomma }}</td></tr><tr><th>Allowances</th><td class="text-end">{{ currency_symbol }}{{ payroll.allowances|floatformat:0|intcomma }}</td></tr><tr><th>Bonus</th><td class="text-end">{{ currency_symbol }}{{ payroll.bonus|floatformat:0|intcomma }}</td></tr><tr><th>Deductions</th><td class="text-end">- {{ currency_symbol }}{{ payroll.deductions|floatformat:0|intcomma }}</td></tr><tr><th>Leave Deductions</th><td class="text-end">- {{ currency_symbol }}{{ payroll.leave_deductions|floatformat:0|intcomma }}</td></tr><tr class="table-active"><th>Net Salary</th><th class="text-end h5">{{ currency_symbol }}{{ payroll.net_salary|floatformat:0|intcomma }}</th></tr></table></div></div>
{% if payroll.payment %}<div class="card"><div class="card-header">Bank Payment</div><div class="card-body p-0"><table class="table mb-0"><tr><th class="w-25">Amount</th><td>{{ currency_symbol }}{{ payroll.payment.amount|floatformat:0|intcomma }}</td></tr><tr><th>Date</th><td>{{ payroll.payment.payment_date|date:"M d, Y" }}</td></tr><tr><th>Method</th><td>{{ payroll.payment.get_method_display }}</td></tr><tr><th>Transaction Ref</th><td>{{ payroll.payment.transaction_ref|default:"—" }}</td></tr><tr><th>Status</th><td>{% if payroll.payment.is_successful %}<span class="badge badge-paid">Successful</span>{% else %}<span class="badge badge-rejected">Failed</span>{% endif %}</td></tr></table></div></div>{% endif %}
</div><div class="col-md-4"><div class="card"><div class="card-header">Status</div><div class="card-body"><span class="badge badge-status badge-{{ payroll.status }} p-3">{{ payroll.get_status_display }}</span><hr><p class="small"><strong>Month:</strong> {{ payroll.month }}</p><p class="small"><strong>Teacher:</strong> {{ payroll.teacher.full_name }}</p><p class="small"><strong>Employee ID:</strong> {{ payroll.teacher.employee_id }}</p><p class="small"><strong>Approved By:</strong> {{ payroll.approved_by|default:"—" }}</p></div></div></div></div>
{% endblock %}
""",
"payroll/payroll_pay.html": """{% extends "base.html" %}{% load crispy_forms_tags %}{% block content %}<h1 class="h3 fw-bold mb-3">Record Bank Payment — {{ payroll.teacher.full_name }}</h1><div class="alert alert-warning"><i class="bi bi-shield-lock me-1"></i> Bank payment records are sensitive and should be entered carefully. The transaction will be locked once recorded.</div><div class="card"><div class="card-body"><div class="mb-3"><strong>Net Salary:</strong> {{ currency_symbol }}{{ payroll.net_salary|floatformat:0|intcomma }} ({{ payroll.month }})</div><form method="post">{% csrf_token %}{{ form|crispy }}<button class="btn btn-primary mt-3"><i class="bi bi-check-lg me-1"></i>Record Payment</button><a href="{% url 'payroll:payroll_detail' payroll.pk %}" class="btn btn-outline-secondary mt-3">Cancel</a></form></div></div>{% endblock %}""",
"payroll/salary_slip.html": """{% extends "base.html" %}
{% block content %}
<div class="container" style="max-width: 700px;"><div class="card"><div class="card-header text-center bg-primary text-white py-3"><h2 class="h4 mb-0">{{ school_name|default:"School ERP" }}</h2><p class="small mb-0">Salary Slip</p></div>
<div class="card-body"><div class="row mb-3"><div class="col-6"><p class="mb-0"><strong>Employee:</strong> {{ payroll.teacher.full_name }}</p><p class="mb-0"><strong>Employee ID:</strong> {{ payroll.teacher.employee_id }}</p><p class="mb-0"><strong>Designation:</strong> {{ payroll.teacher.designation|default:"—" }}</p></div><div class="col-6 text-end"><p class="mb-0"><strong>Month:</strong> {{ payroll.month }}</p><p class="mb-0"><strong>Status:</strong> {{ payroll.get_status_display }}</p></div></div>
<hr><table class="table table-bordered"><thead><tr><th>Description</th><th class="text-end">Amount</th></tr></thead><tbody><tr><td>Basic Salary</td><td class="text-end">{{ currency_symbol }}{{ payroll.basic_salary|floatformat:0|intcomma }}</td></tr><tr><td>Allowances</td><td class="text-end">{{ currency_symbol }}{{ payroll.allowances|floatformat:0|intcomma }}</td></tr><tr><td>Bonus</td><td class="text-end">{{ currency_symbol }}{{ payroll.bonus|floatformat:0|intcomma }}</td></tr><tr><td>Deductions</td><td class="text-end">- {{ currency_symbol }}{{ payroll.deductions|floatformat:0|intcomma }}</td></tr><tr><td>Leave Deductions</td><td class="text-end">- {{ currency_symbol }}{{ payroll.leave_deductions|floatformat:0|intcomma }}</td></tr></tbody><tfoot><tr class="table-active"><th>Net Salary</th><th class="text-end h5">{{ currency_symbol }}{{ payroll.net_salary|floatformat:0|intcomma }}</th></tr></tfoot></table>
{% if payroll.payment %}<div class="alert alert-success"><strong><i class="bi bi-check-circle me-1"></i>Paid</strong> on {{ payroll.payment.payment_date|date:"M d, Y" }} via {{ payroll.payment.get_method_display }}.</div>{% endif %}
<p class="small text-muted-2 mt-3">This is a computer-generated salary slip and does not require a physical signature.</p>
</div></div></div>
{% endblock %}
""",
# Activities
"activities/activity_list.html": """{% extends "base.html" %}{% block content %}<div class="d-flex justify-content-between align-items-center mb-3"><h1 class="h3 fw-bold mb-0">Activities</h1>{% if perms.activities.add_activity %}<a href="{% url 'activities:activity_create' %}" class="btn btn-primary"><i class="bi bi-plus me-1"></i>New Activity</a>{% endif %}</div><div class="card mb-3"><div class="card-body"><form method="get"><select name="category" class="form-select"><option value="">— All Categories —</option>{% for c,l in category_choices %}<option value="{{ c }}" {% if request.GET.category == c %}selected{% endif %}>{{ l }}</option>{% endfor %}</select></form></div></div><div class="row g-3">{% for a in activities %}<div class="col-md-6"><div class="card h-100"><div class="card-body"><div class="d-flex justify-content-between"><span class="badge bg-soft-primary">{{ a.get_category_display }}</span><small class="text-muted-2">{{ a.date|date:"M d, Y" }}</small></div><h5 class="mt-2 mb-1">{{ a.title }}</h5><p class="small text-muted-2">{{ a.description|truncatewords:25 }}</p>{% if a.location %}<p class="small"><i class="bi bi-geo-alt me-1"></i>{{ a.location }}</p>{% endif %}</div></div></div>{% empty %}<div class="col-12"><div class="empty-state"><i class="bi bi-trophy"></i><p>No activities yet.</p></div></div>{% endfor %}</div>{% endblock %}""",
"activities/activity_form.html": """{% extends "base.html" %}{% load crispy_forms_tags %}{% block content %}<h1 class="h3 fw-bold mb-3">New Activity</h1><div class="card"><div class="card-body"><form method="post" enctype="multipart/form-data">{% csrf_token %}{{ form|crispy }}<button class="btn btn-primary mt-3">Save</button><a href="{% url 'activities:activity_list' %}" class="btn btn-outline-secondary mt-3">Cancel</a></form></div></div>{% endblock %}""",
"activities/activity_detail.html": """{% extends "base.html" %}{% block content %}<div class="d-flex justify-content-between align-items-center mb-3"><h1 class="h3 fw-bold mb-0">{{ activity.title }}</h1><span class="badge bg-soft-primary">{{ activity.get_category_display }}</span></div><div class="card mb-3"><div class="card-header">Details</div><div class="card-body p-0"><table class="table mb-0"><tr><th class="w-25">Date</th><td>{{ activity.date|date:"l, M d, Y" }}</td></tr><tr><th>Location</th><td>{{ activity.location|default:"—" }}</td></tr><tr><th>Academic Year</th><td>{{ activity.academic_year.name }}</td></tr></table></div></div><div class="card"><div class="card-header">Description</div><div class="card-body">{{ activity.description|linebreaksbr }}{% if activity.result %}<hr><h6>Result</h6><p>{{ activity.result|linebreaksbr }}</p>{% endif %}</div></div>{% endblock %}""",
# Announcements
"announcements/list.html": """{% extends "base.html" %}{% block content %}<div class="d-flex justify-content-between align-items-center mb-3"><h1 class="h3 fw-bold mb-0">Announcements</h1>{% if perms.announcements.add_announcement %}<a href="{% url 'announcements:create' %}" class="btn btn-primary"><i class="bi bi-megaphone me-1"></i>New Announcement</a>{% endif %}</div><div class="row g-3">{% for a in announcements %}<div class="col-md-6"><div class="card h-100"><div class="card-body"><div class="d-flex justify-content-between"><span class="badge bg-soft-primary">{{ a.get_audience_display }}</span><small class="text-muted-2">{{ a.publish_date|date:"M d, Y" }}</small></div><h5 class="mt-2 mb-1">{{ a.title }}</h5><p class="small text-muted-2">{{ a.description|truncatewords:25 }}</p><a href="{% url 'announcements:detail' a.pk %}" class="btn btn-sm btn-outline-primary">Read more</a></div></div></div>{% empty %}<div class="col-12"><div class="empty-state"><i class="bi bi-megaphone"></i><p>No announcements yet.</p></div></div>{% endfor %}</div>{% endblock %}""",
"announcements/form.html": """{% extends "base.html" %}{% load crispy_forms_tags %}{% block content %}<h1 class="h3 fw-bold mb-3">New Announcement</h1><div class="card"><div class="card-body"><form method="post" enctype="multipart/form-data">{% csrf_token %}{{ form|crispy }}<button class="btn btn-primary mt-3"><i class="bi bi-megaphone me-1"></i>Publish</button><a href="{% url 'announcements:list' %}" class="btn btn-outline-secondary mt-3">Cancel</a></form></div></div>{% endblock %}""",
"announcements/detail.html": """{% extends "base.html" %}{% block content %}<div class="d-flex justify-content-between align-items-center mb-3"><h1 class="h3 fw-bold mb-0">{{ announcement.title }}</h1><span class="badge bg-soft-primary">{{ announcement.get_audience_display }}</span></div><div class="card mb-3"><div class="card-body"><p class="small text-muted-2 mb-2"><i class="bi bi-person me-1"></i>{{ announcement.author|default:"System" }} · <i class="bi bi-clock me-1"></i>{{ announcement.publish_date|date:"M d, Y H:i" }}</p><hr>{{ announcement.description|linebreaksbr }}</div></div>{% if announcement.attachment %}<a href="{{ announcement.attachment.url }}" class="btn btn-outline-primary"><i class="bi bi-paperclip me-1"></i>Download Attachment</a>{% endif %}<a href="{% url 'announcements:list' %}" class="btn btn-outline-secondary">Back</a>{% endblock %}""",
# Notifications
"notifications/list.html": """{% extends "base.html" %}{% block content %}<h1 class="h3 fw-bold mb-3">Notifications</h1><div class="card"><div class="card-body p-0">{% if notifications %}<ul class="list-group list-group-flush">{% for n in notifications %}<li class="list-group-item d-flex justify-content-between align-items-start {% if not n.is_read %}bg-soft-primary{% endif %}"><div><div class="fw-bold">{{ n.title }}</div><div class="small text-muted-2">{{ n.message|truncatewords:30 }}</div><div class="small text-muted-2 mt-1">{{ n.sent_at|date:"M d, Y H:i" }}</div></div>{% if not n.is_read %}<form method="post" action="{% url 'notifications:mark_read' n.pk %}">{% csrf_token %}<button class="btn btn-sm btn-outline-primary">Mark as read</button></form>{% endif %}</li>{% endfor %}</ul>{% else %}<div class="empty-state"><i class="bi bi-bell-slash"></i><p>No notifications yet.</p></div>{% endif %}</div></div>{% endblock %}""",
# Calendar
"school_calendar/event_list.html": """{% extends "base.html" %}{% block content %}<div class="d-flex justify-content-between align-items-center mb-3"><h1 class="h3 fw-bold mb-0">School Calendar</h1>{% if perms.school_calendar.add_calendarevent %}<a href="{% url 'school_calendar:event_create' %}" class="btn btn-primary"><i class="bi bi-plus me-1"></i>New Event</a>{% endif %}</div><div class="card"><div class="card-body p-0">{% if events %}<table class="table table-hover mb-0"><thead><tr><th>Date</th><th>Event</th><th>Category</th><th>Location</th></tr></thead><tbody>{% for e in events %}<tr><td>{{ e.start_date|date:"M d, Y" }}</td><td><strong>{{ e.title }}</strong></td><td><span class="badge bg-soft-primary">{{ e.get_category_display }}</span></td><td>{{ e.location|default:"—" }}</td></tr>{% endfor %}</tbody></table>{% else %}<div class="empty-state"><i class="bi bi-calendar-event"></i></div>{% endif %}</div></div>{% endblock %}""",
"school_calendar/event_form.html": """{% extends "base.html" %}{% load crispy_forms_tags %}{% block content %}<h1 class="h3 fw-bold mb-3">New Calendar Event</h1><div class="card"><div class="card-body"><form method="post">{% csrf_token %}{{ form|crispy }}<button class="btn btn-primary mt-3">Save</button><a href="{% url 'school_calendar:event_list' %}" class="btn btn-outline-secondary mt-3">Cancel</a></form></div></div>{% endblock %}""",
# Reports
"reports/index.html": """{% extends "base.html" %}{% block content %}<h1 class="h3 fw-bold mb-3">Report Center</h1><div class="row g-3"><div class="col-md-4"><div class="card h-100"><div class="card-body"><i class="bi bi-mortarboard display-6 text-primary"></i><h5 class="mt-2">Student Report</h5><p class="small text-muted-2">All registered students with their status and enrollment history.</p><a href="{% url 'reports:student_report' %}" class="btn btn-outline-primary btn-sm">Open</a></div></div></div><div class="col-md-4"><div class="card h-100"><div class="card-body"><i class="bi bi-receipt display-6 text-success"></i><h5 class="mt-2">Fee Report</h5><p class="small text-muted-2">Challans, payments collected, outstanding balances.</p><a href="{% url 'reports:fee_report' %}" class="btn btn-outline-primary btn-sm">Open</a></div></div></div><div class="col-md-4"><div class="card h-100"><div class="card-body"><i class="bi bi-exclamation-triangle display-6 text-warning"></i><h5 class="mt-2">Defaulter Report (PDF)</h5><p class="small text-muted-2">All students with outstanding fees, exportable as PDF.</p><a href="{% url 'reports:defaulter_pdf' %}" target="_blank" class="btn btn-outline-primary btn-sm"><i class="bi bi-file-pdf me-1"></i>Download PDF</a></div></div></div><div class="col-md-4"><div class="card h-100"><div class="card-body"><i class="bi bi-clipboard-data display-6 text-info"></i><h5 class="mt-2">Attendance Report</h5><p class="small text-muted-2">Daily attendance records and trends.</p><a href="{% url 'reports:attendance_report' %}" class="btn btn-outline-primary btn-sm">Open</a></div></div></div>{% if request.user.can_view_payroll %}<div class="col-md-4"><div class="card h-100"><div class="card-body"><i class="bi bi-cash-coin display-6 text-danger"></i><h5 class="mt-2">Payroll Report</h5><p class="small text-muted-2">Teacher salaries, payments, monthly totals.</p><a href="{% url 'reports:payroll_report' %}" class="btn btn-outline-primary btn-sm">Open</a></div></div></div>{% endif %}</div>{% endblock %}""",
"reports/student_report.html": """{% extends "base.html" %}{% block content %}<h1 class="h3 fw-bold mb-3">Student Report</h1><div class="card"><div class="card-body p-0">{% if students %}<table class="table table-hover mb-0"><thead><tr><th>Reg #</th><th>Name</th><th>Class</th><th>Status</th><th>Admission Date</th></tr></thead><tbody>{% for s in students %}<tr><td>{{ s.registration_no }}</td><td>{{ s.full_name }}</td><td>{{ s.class_section_display }}</td><td>{{ s.get_status_display }}</td><td>{{ s.admission_date|date:"M d, Y" }}</td></tr>{% endfor %}</tbody></table>{% else %}<div class="empty-state"><i class="bi bi-people"></i></div>{% endif %}</div></div>{% endblock %}""",
"reports/fee_report.html": """{% extends "base.html" %}{% block content %}<h1 class="h3 fw-bold mb-3">Fee Report</h1><div class="row g-3 mb-3"><div class="col-md-6"><div class="stat-card"><div class="stat-icon bg-soft-success"><i class="bi bi-cash-coin"></i></div><div class="stat-label">Total Collected</div><div class="stat-value text-success">{{ currency_symbol }}{{ total_collected|floatformat:0|intcomma }}</div></div></div><div class="col-md-6"><div class="stat-card"><div class="stat-icon bg-soft-danger"><i class="bi bi-exclamation-triangle"></i></div><div class="stat-label">Total Outstanding</div><div class="stat-value text-danger">{{ currency_symbol }}{{ total_outstanding|floatformat:0|intcomma }}</div></div></div></div><div class="card"><div class="card-body p-0">{% if challans %}<table class="table table-hover mb-0"><thead><tr><th>Challan #</th><th>Student</th><th>Month</th><th>Payable</th><th>Paid</th><th>Balance</th><th>Status</th></tr></thead><tbody>{% for c in challans %}<tr><td>{{ c.challan_no }}</td><td>{{ c.student.full_name }}</td><td>{{ c.month|default:"—" }}</td><td>{{ currency_symbol }}{{ c.total_payable|floatformat:0|intcomma }}</td><td class="text-success">{{ currency_symbol }}{{ c.total_paid|floatformat:0|intcomma }}</td><td class="text-danger">{{ currency_symbol }}{{ c.balance|floatformat:0|intcomma }}</td><td><span class="badge badge-status badge-{{ c.status }}">{{ c.get_status_display }}</span></td></tr>{% endfor %}</tbody></table>{% else %}<div class="empty-state"><i class="bi bi-receipt"></i></div>{% endif %}</div></div>{% endblock %}""",
"reports/attendance_report.html": """{% extends "base.html" %}{% block content %}<h1 class="h3 fw-bold mb-3">Attendance Report</h1><div class="card"><div class="card-body p-0">{% if records %}<table class="table table-hover mb-0"><thead><tr><th>Date</th><th>Student</th><th>Class</th><th>Status</th></tr></thead><tbody>{% for r in records %}<tr><td>{{ r.date|date:"M d, Y" }}</td><td>{{ r.student.full_name }}</td><td>{{ r.school_class.name }}</td><td><span class="badge {% if r.status == 'present' %}bg-soft-success{% elif r.status == 'absent' %}bg-soft-danger{% elif r.status == 'late' %}bg-soft-warning{% else %}bg-soft-info{% endif %}">{{ r.get_status_display }}</span></td></tr>{% endfor %}</tbody></table>{% else %}<div class="empty-state"><i class="bi bi-clipboard-data"></i></div>{% endif %}</div></div>{% endblock %}""",
"reports/payroll_report.html": """{% extends "base.html" %}{% block content %}<h1 class="h3 fw-bold mb-3">Payroll Report</h1><div class="card"><div class="card-body p-0">{% if payrolls %}<table class="table table-hover mb-0"><thead><tr><th>Teacher</th><th>Month</th><th>Net Salary</th><th>Status</th></tr></thead><tbody>{% for p in payrolls %}<tr><td>{{ p.teacher.full_name }}</td><td>{{ p.month }}</td><td>{{ currency_symbol }}{{ p.net_salary|floatformat:0|intcomma }}</td><td><span class="badge badge-status badge-{{ p.status }}">{{ p.get_status_display }}</span></td></tr>{% endfor %}</tbody></table>{% else %}<div class="empty-state"><i class="bi bi-cash-coin"></i></div>{% endif %}</div></div>{% endblock %}""",
"reports/defaulter_pdf.html": """{% extends "base.html" %}{% block content %}<div class="container"><div class="text-center mb-4"><h2>{{ school_name|default:"School ERP" }}</h2><h4>Fee Defaulter Report</h4><p class="small">Generated on {% now "M d, Y H:i" %}</p><p class="h3">Total Outstanding: {{ currency_symbol }}{{ total_outstanding|floatformat:0|intcomma }}</p></div><table class="table table-bordered"><thead><tr><th>Challan #</th><th>Student</th><th>Class</th><th>Month</th><th>Balance</th><th>Status</th><th>Due Date</th></tr></thead><tbody>{% for c in challans %}<tr><td>{{ c.challan_no }}</td><td>{{ c.student.full_name }}</td><td>{{ c.student.class_section_display }}</td><td>{{ c.month|default:"—" }}</td><td>{{ currency_symbol }}{{ c.balance|floatformat:0|intcomma }}</td><td>{{ c.get_status_display }}</td><td>{{ c.due_date|date:"M d, Y"|default:"—" }}</td></tr>{% endfor %}</tbody></table></div>{% endblock %}""",
# Audit logs
"audit_logs/log_list.html": """{% extends "base.html" %}{% block content %}<h1 class="h3 fw-bold mb-3">Audit Logs</h1><div class="card mb-3"><div class="card-body"><form method="get" class="row g-2"><div class="col-md-4"><input type="text" name="q" class="form-control" placeholder="Search description or object" value="{{ request.GET.q }}"></div><div class="col-md-3"><select name="action" class="form-select"><option value="">— All Actions —</option>{% for s,label in action_choices %}<option value="{{ s }}" {% if request.GET.action == s %}selected{% endif %}>{{ label }}</option>{% endfor %}</select></div><div class="col-md-2"><button class="btn btn-outline-primary w-100">Filter</button></div></form></div></div><div class="card"><div class="card-body p-0">{% if logs %}<table class="table table-hover mb-0"><thead><tr><th>Timestamp</th><th>User</th><th>Action</th><th>Object</th><th>Description</th></tr></thead><tbody>{% for log in logs %}<tr><td>{{ log.timestamp|date:"M d, Y H:i" }}</td><td>{{ log.user|default:"System" }}</td><td><span class="badge bg-soft-primary">{{ log.get_action_display }}</span></td><td>{{ log.object_repr }}</td><td>{{ log.description|truncatewords:15 }}</td></tr>{% endfor %}</tbody></table>{% else %}<div class="empty-state"><i class="bi bi-clock-history"></i></div>{% endif %}</div></div>{% endblock %}""",
# Portals
"portal/student_home.html": """{% extends "base.html" %}{% block content %}{% if student %}<div class="mb-3"><h1 class="h3 fw-bold mb-0">Welcome, {{ student.full_name|slice:":1" }}{{ student.full_name|slice:"1:" }}</h1><p class="text-muted-2 small mb-0">Class: {{ student.class_section_display }} · Registration: {{ student.registration_no }}</p></div><div class="row g-3 mb-4"><div class="col-6 col-md-3"><div class="stat-card"><div class="stat-icon bg-soft-success"><i class="bi bi-check-circle"></i></div><div class="stat-label">Attendance</div><div class="stat-value">{{ attendance_percentage }}%</div></div></div><div class="col-6 col-md-3"><div class="stat-card"><div class="stat-icon bg-soft-warning"><i class="bi bi-credit-card"></i></div><div class="stat-label">Fee Status</div><div class="stat-value">{% if pending_challans %}Pending{% else %}Paid{% endif %}</div></div></div><div class="col-6 col-md-3"><div class="stat-card"><div class="stat-icon bg-soft-primary"><i class="bi bi-pencil-square"></i></div><div class="stat-label">Pending Homework</div><div class="stat-value">{{ upcoming_homework|length }}</div></div></div><div class="col-6 col-md-3"><div class="stat-card"><div class="stat-icon bg-soft-info"><i class="bi bi-journal-medical"></i></div><div class="stat-label">Upcoming Tests</div><div class="stat-value">{{ upcoming_tests|length }}</div></div></div></div><div class="row g-3"><div class="col-md-6"><div class="card"><div class="card-header">Pending Challans</div><div class="card-body p-0">{% if pending_challans %}<ul class="list-group list-group-flush">{% for c in pending_challans %}<li class="list-group-item d-flex justify-content-between"><div><strong>{{ c.challan_no }}</strong><br><small class="text-muted-2">{{ c.month|default:"" }} · Due {{ c.due_date|date:"M d, Y" }}</small></div><span class="badge badge-status badge-{{ c.status }}">{{ c.get_status_display }}</span></li>{% endfor %}</ul>{% else %}<div class="empty-state"><i class="bi bi-check-circle"></i><p>All fees are paid!</p></div>{% endif %}</div></div></div><div class="col-md-6"><div class="card"><div class="card-header">Recent Test Results</div><div class="card-body p-0">{% if test_results %}<ul class="list-group list-group-flush">{% for r in test_results %}<li class="list-group-item d-flex justify-content-between"><div><strong>{{ r.test.title }}</strong><br><small class="text-muted-2">{{ r.test.subject.name|default:"" }} · {{ r.test.date|date:"M d, Y" }}</small></div><span class="badge bg-soft-primary">{{ r.obtained_marks|floatformat:0 }}/{{ r.test.total_marks|floatformat:0 }}</span></li>{% endfor %}</ul>{% else %}<div class="empty-state"><i class="bi bi-clipboard"></i></div>{% endif %}</div></div></div></div>{% else %}<div class="alert alert-warning">No student profile linked to your account. Please contact the school administration.</div>{% endif %}{% endblock %}""",
"portal/teacher_home.html": """{% extends "base.html" %}{% block content %}{% if teacher %}<div class="mb-3"><h1 class="h3 fw-bold mb-0">Welcome, {{ teacher.full_name }}</h1><p class="text-muted-2 small mb-0">Employee ID: {{ teacher.employee_id }} · Designation: {{ teacher.designation|default:"—" }}</p></div><div class="row g-3 mb-4"><div class="col-6 col-md-3"><div class="stat-card"><div class="stat-icon bg-soft-primary"><i class="bi bi-mortarboard"></i></div><div class="stat-label">My Classes</div><div class="stat-value">{{ my_classes.count }}</div></div></div><div class="col-6 col-md-3"><div class="stat-card"><div class="stat-icon bg-soft-info"><i class="bi bi-journal-bookmark"></i></div><div class="stat-label">My Subjects</div><div class="stat-value">{{ my_subjects.count }}</div></div></div><div class="row g-3"><div class="col-md-6"><div class="card"><div class="card-header">My Classes</div><div class="card-body p-0"><ul class="list-group list-group-flush">{% for c in my_classes %}<li class="list-group-item">{{ c.name }}</li>{% empty %}<li class="list-group-item text-muted-2">No classes assigned</li>{% endfor %}</ul></div></div></div><div class="col-md-6"><div class="card"><div class="card-header">My Subjects</div><div class="card-body p-0"><ul class="list-group list-group-flush">{% for s in my_subjects %}<li class="list-group-item">{{ s.name }}</li>{% empty %}<li class="list-group-item text-muted-2">No subjects assigned</li>{% endfor %}</ul></div></div></div></div>{% else %}<div class="alert alert-warning">No teacher profile linked to your account. Please contact the school administration.</div>{% endif %}{% endblock %}""",
"portal/parent_home.html": """{% extends "base.html" %}{% block content %}{% if parent %}<div class="mb-3"><h1 class="h3 fw-bold mb-0">Welcome, {{ parent.full_name }}</h1><p class="text-muted-2 small mb-0">{{ parent.get_relation_display }} · Phone: {{ parent.phone|default:"—" }}</p></div><div class="row g-3">{% if children %}{% for c in children %}<div class="col-md-6"><div class="card h-100"><div class="card-body"><div class="d-flex justify-content-between align-items-center"><h5 class="mb-0"><a href="{% url 'students:student_detail' c.pk %}">{{ c.full_name }}</a></h5><span class="badge {% if c.status == 'active' %}badge-paid{% else %}badge-draft{% endif %}">{{ c.get_status_display }}</span></div><p class="small text-muted-2 mb-0 mt-1">{{ c.registration_no }} · Class {{ c.class_section_display }}</p></div></div></div>{% endfor %}{% else %}<div class="col-12"><div class="empty-state"><i class="bi bi-people"></i><p>No children linked.</p></div></div>{% endif %}</div>{% else %}<div class="alert alert-warning">No parent profile linked to your account.</div>{% endif %}{% endblock %}""",
}

for tmpl_path, content in TEMPLATES.items():
    full_path = os.path.join(BASE, tmpl_path)
    os.makedirs(os.path.dirname(full_path), exist_ok=True)
    with open(full_path, "w") as f:
        f.write(content)

print(f"Created {len(TEMPLATES)} templates")
