# Generated by Django 4.2 on 2026-10-02 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('father_name', models.CharField(blank=True, max_length=200)),
                ('cnic', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('photograph', models.ImageField(blank=True, null=True, upload_to='teachers/')),
                ('qualification', models.CharField(blank=True, max_length=200)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('resigned', 'Resigned')], db_index=True, default='active', max_length=10)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('classes', models.ManyToManyField(blank=True, related_name='teachers', to='common.schoolclass')),
                ('sections', models.ManyToManyField(blank=True, related_name='teachers', to='common.section')),
                ('subjects', models.ManyToManyField(blank=True, related_name='teachers', to='common.subject')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherBankInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_name', models.CharField(max_length=200)),
                ('branch', models.CharField(blank=True, max_length=200)),
                ('account_title', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=50)),
                ('iban', models.CharField(blank=True, max_length=50)),
                ('swift_code', models.CharField(blank=True, max_length=20)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_info', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Teacher Bank Information',
                'verbose_name_plural': 'Teacher Bank Information',
            },
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['status'], name='teachers_te_status_cc7a79_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['employee_id'], name='teachers_te_employe_8033d0_idx'),
        ),
    ]
