# Generated by Django 4.2.30 on 2026-10-03 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='staff_category',
            field=models.CharField(choices=[('teaching', 'Teaching Staff'), ('admin', 'Administration Staff'), ('support', 'Support Staff')], db_index=True, default='teaching', max_length=10),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teaching_level',
            field=models.CharField(choices=[('primary', 'Primary (Grade 1-5)'), ('middle', 'Middle (Grade 6-8)'), ('secondary', 'Secondary (Grade 9-10)'), ('all', 'All Levels')], db_index=True, default='all', max_length=12),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['teaching_level', 'staff_category'], name='teachers_te_teachin_73bdf2_idx'),
        ),
    ]
