# Generated by Django 4.2 on 2026-10-02 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('holiday', 'Holiday'), ('exam', 'Exam'), ('test', 'Test'), ('parent_meeting', 'Parent Meeting'), ('event', 'Event'), ('sports_day', 'Sports Day'), ('annual_function', 'Annual Function'), ('trip', 'Trip'), ('deadline', 'Deadline')], default='event', max_length=15)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_public', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='common.academicyear')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
