# Generated by Django 4.2 on 2026-10-02 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term', models.CharField(choices=[('first', 'First Term'), ('second', 'Second Term'), ('final', 'Final Term'), ('mid', 'Mid Term')], default='first', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='syllabi', to='common.academicyear')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to='common.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='syllabi', to='common.subject')),
            ],
            options={
                'ordering': ['academic_year', 'school_class', 'term', 'subject'],
            },
        ),
        migrations.CreateModel(
            name='SyllabusTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('expected_completion_date', models.DateField(blank=True, null=True)),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('priority', models.PositiveIntegerField(default=3, help_text='1=High, 5=Low')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('delayed', 'Delayed')], db_index=True, default='not_started', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='syllabus.syllabus')),
            ],
            options={
                'ordering': ['syllabus', 'priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LecturePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('learning_objectives', models.TextField(blank=True)),
                ('lecture_content', models.TextField(blank=True)),
                ('activities', models.TextField(blank=True)),
                ('homework', models.TextField(blank=True)),
                ('resources', models.TextField(blank=True)),
                ('estimated_duration', models.PositiveIntegerField(default=40, help_text='in minutes')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('planned', 'Planned'), ('completed', 'Completed')], db_index=True, default='draft', max_length=10)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lecture_plans', to='common.academicyear')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_plans', to='common.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lecture_plans', to='common.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecture_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='syllabustopic',
            index=models.Index(fields=['status'], name='syllabus_sy_status_d0fdce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='syllabus',
            unique_together={('academic_year', 'school_class', 'subject', 'term')},
        ),
    ]
